language: swift
xcode_project: ThunderCollection.xcodeproj # path to your xcodeproj folder
osx_image: xcode12
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
matrix:
  include:
    - xcode_scheme: ThunderCollection
      xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone 11 Pro Max
