language: swift
xcode_project: ThunderCollection.xcodeproj # path to your xcodeproj folder
osx_image: xcode10.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
matrix:
  include:
    - xcode_scheme: ThunderCollection
      xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone XS Max
